---
name: smd
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - numpy
  - numba
  - matplotlib=3.8
  - scipy=1.12
  - pandas=2
  - scikit-learn=1.4
  - ipython=8
  - ipympl
  - jupyterlab
  - jupyter
  - notebook
  - pytest
  - pytables
  - tqdm
  - click=8
  - pre-commit
  - ruff
